# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'emojiman' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emojiman
  pod 'Google-Mobile-Ads-SDK'

  pod 'RNFS', :path => '../node_modules/react-native-fs'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  target 'emojimanTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'emojiman-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for emojiman-tvOS

  target 'emojiman-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
